name: publish-cron

on:
  push:
    branches: [fix-dependency-version-remove-gradle-recipe]
  schedule:
    - cron: '0 12 * * *'

jobs:
  publish:
    name: publish azure-spring-rewrite tp github package repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@main

      - name: Publish package
        uses: gradle/gradle-build-action@main
        with:
          arguments: snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}