# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: publish-cron

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  publish:
    name: publish azure-spring-rewrite tp github package repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@master

      - run: git pull

      - run: echo "$(git describe --tags --first-parent)"

      - run: echo "$(git describe --tags --always --first-parent)"

      - run: echo "$(git describe --tags --abbrev=0 --always --first-parent)"

      - run: echo "$(git describe --tags --abbrev=0 --always)"


      - name: Publish package
        uses: gradle/gradle-build-action@main
        with:
          arguments: snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}